name: stack-practice
version: 0.1.0
github: simnalamburt/stack-practice
license: (Apache-2.0 OR MIT)
author: Hyeon Kim
maintainer: simnalamburt@gmail.com
copyright: 2015-2021 Hyeon Kim

extra-source-files:
- README.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/simnalamburt/stack-practice#readme>

dependencies:
- base >= 4.7 && < 5

executables:
  stack-practice-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - scotty
    - aeson

tests:
  stack-practice-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
